stages:
  - test
  - build
  - package

include:
  - template: Security/SAST.gitlab-ci.yml

default:
  tags:
    - linux
    - docker

variables:
  CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX: registry.gitlab.com/kingkingyyk/containers

.base-py:
  image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/python:3.13-slim-bookworm
  before_script:
    - apt update
    - apt install gcc libpq-dev g++ libffi-dev make mime-support -y
    - pip install -r backend/.req/dev.txt
    - pip install -r backend/.req/ci.txt

.base-node:
  image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/node:24.0-alpine3.20

lint-backend:
  extends: .base-py
  stage: test
  script:
    - cd backend
    - cp ../.ci/config-test.yaml config.yaml
    - black . --check
    - python -m pylint
      --rcfile .pylintrc
      backend
      rpidrive

sast-backend:
  extends: .base-py
  stage: test
  script:
    - cd backend
    - bandit -l -r -v .

test-backend:
  extends: .base-py
  stage: test
  services:
    - name: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/redis:8.0.0-alpine
      alias: redis
    - name: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/postgres:17.5-alpine
      alias: postgres
  variables:
    REDIS_PORT: 6379
    REDIS_HOST: redis
    REDIS_DB: 0
    POSTGRES_DB: rpidrive
    POSTGRES_USER: heh
    POSTGRES_PASSWORD: anya;peanutz!1
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - cd backend
    - cp ../.ci/config-test.yaml config.yaml
    - python manage.py makemigrations rpidrive
    - python manage.py migrate
    - coverage run -m pytest --ds=backend.settings --junitxml=test-reports/unit-test.xml
    - coverage report --show-missing --precision=2
    - coverage xml -o ./test-reports/unit-test-coverage.xml
    - coverage xml
    - anybadge --value=$(python ../.ci/print-junit-pass-rate.py test-reports/unit-test.xml) --label='unit test' --file='unit-test-badge.svg' coverage
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: backend/test-reports/unit-test-coverage.xml
      junit: backend/test-reports/unit-test.xml
    paths:
      - backend/unit-test-badge.svg
  coverage: '/^TOTAL.+?(\d+.\d+\%)$/'

test-frontend:
  extends: .base-node
  stage: test
  script:
    - cd frontend
    - npm ci
    - npm run lint

sast:
  stage: test

build-frontend:
  extends: .base-node
  stage: build
  script:
    - cd frontend
    - npm ci
    - npm run build
    - cd ..
    - mv frontend/build/static/* backend/static/
    - mv frontend/build/index.html backend/rpidrive/templates/
    - mv frontend/build/favicon.ico backend/static/
  artifacts:
    paths:
      - backend/
    expire_in: 1 hour

.package-docker:
  image: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/jdrouet/docker-with-buildx:stable
  stage: package
  tags:
    - linux
    - docker
  services:
    - name: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/docker:dind
      alias: docker
  dependencies:
    - build-frontend
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    CI_REGISTRY: registry.gitlab.com
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
    - docker buildx build --platform $ARCH -t $CI_IMAGE_TAG -f dockerfile --build-arg IMAGE_PROXY=$CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX --push .
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        CI_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      when: always
    - if: $CI_COMMIT_BRANCH
      variables:
        CI_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
      when: always

package-amd64-docker:
  extends: .package-docker
  variables:
    ARCH: linux/amd64

package-multiarch-docker:
  extends: .package-docker
  variables:
    ARCH: linux/arm/v7,linux/arm64/v8,linux/amd64
  when: manual
