stages:
  - test

"Test Backend":
  image: python:3.9-slim-buster
  stage: test
  script:
    - cd backend
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - coverage run -m pytest --ds=rpidrive.settings --junitxml=./test-reports/unit-test.xml
    - coverage report --show-missing
    - coverage xml -o ./test-reports/unit-test-coverage.xml
    - coverage xml
  artifacts:
    reports:
      cobertuna: ./test-reports/unit-test-coverage.xml
      junit: ./test-reports/unit-test.xml
  coverage: '^TOTAL.*\s+(\d+\%)$'