stages:
  - build
  - package

build:
  image: node:15-alpine
  stage: build
  script:
    - sh scripts/gitlab-build.sh
  artifacts:
    paths:
      - build/

package:zip:
  image: alpine:3
  stage: package
  needs: ["build"]
  script:
    - tar -czvf build.tar.gz build/*
  artifacts:
    paths:
      - build.tar.gz

package:docker:
  image: jdrouet/docker-with-buildx:stable
  stage: package
  needs: ["build"]
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    CI_REGISTRY: registry.gitlab.com
    CI_IMAGE_TAG: $CI_REGISTRY/kingkingyyk/rpidrive:$CI_COMMIT_REF_NAME
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
    - docker buildx build --platform linux/arm/v7,linux/amd64 -t $CI_IMAGE_TAG -f dockerfile .
    - docker push $CI_IMAGE_TAG