version: "3.8"
services:
  redis:
    image: "redis:7.2.1-bookworm"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - /home/lel/rpidrive-data/redis:/data
  db:
    image: "postgres:16.0"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'uS3r'
      POSTGRES_PASSWORD: 'pAssw0rd'
      POSTGRES_DB: 'rpidrive'
    volumes:
      - /home/lel/rpidrive-data/postgres:/var/lib/postgresql/data
