from .compress_view import *
from .delete_view import *
from .detail_view import *
from .move_view import *
from .new_folder_view import *
from .qa_view import *
from .rename_view import *
from .search_view import *
from .share_view import *
from .thumbnail_view import *
from .upload_view import *
