web:
  debug: false
  secret-key: "0#-f!3ku(zwq^(nd!5!mu-%zou^+hy-9b5g1#f$9idqwx^6@6!"
  time-zone: "Asia/Kuala_Lumpur"
indexer:
  period: 180
database:
  host: "postgres"
  port: 5432
  name: "rpidrive"
  user: "heh"
  password: "anya;peanutz!1"
redis:
  host: "redis"
  port: 6379
  db: 0
security:
  block-spam: true
  block-trigger: 5
  block-duration: 600
  domain:
    - http://localhost:8000
reverse-proxy:
  ip-header: null
