version: '3'
services:
  database:
    image: postgres:latest
    command: postgres -c 'max_connections=500'
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rpidrive
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  download:
    image: ndthuan/aria2-alpine
    ports:
      - "6800:6800"
    environment:
      RPC_SECRET: rpidrive
    volumes:
      - $HOME/shared/Downloads:/downloads