name: Compile & Package
on: push
jobs:
  cleanup-backend:
    name: Cleanup Backend Files
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup backend
        working-directory: ./backend
        run: |
          rm -Rf static/drive
          rm RPiDrive_ng/settings/dev.py
          rm RPiDrive_ng/settings/prod.py
  compile-frontend:
    name: Compile Frontend
    runs-on: ubuntu-latest
    needs: cleanup-backend
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Compile Frontend
        working-directory: ./frontend
        run: |
          npm install @angular/cli -g
          npm install
          ng build --prod --aot --deployUrl=/static/drive/ --outputPath=../backend/static/drive/
      - name: Patch backend
        working-directory: ./backend
        run: |
          mv -f static/drive/index.html drive/templates/drive/index.html
  generate-zip-build:
    name: Generate Zip Build
    needs: compile-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Upload code
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: backend/