name: Compile Frontend
on: push
jobs:
  compile-frontend:
    name: Compile Frontend
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install @angular/cli -g
      - run: npm install
      - run: ng build build --prod --aot --deployUrl=/static/drive/ --outputPath=../backend/static/drive/
